### ISSUE TITLE
Convert channels to NeuroML 2 for use in exported cell models

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/SmithEtAl2013-L23DendriticSpikes#1]
Make a list and add it here...

**Comment by borismarin** [comment]
- [ ] na.mod -> [na.channel.nml](NeuroML2/na.channel.nml)
- [ ] kv.mod -> [kv.channel.nml](NeuroML2/kv.channel.nml) 
- [ ] km.mod -> [km.channel.nml](NeuroML2/km.channel.nml)
- [ ] kca.mod -> [kca.channel.nml](NeuroML2/kca.channel.nml)
- [ ] ca.mod -> [ca.channel.nml](NeuroML2/ca.channel.nml)
- [ ] CaT.mod -> [it.channel.nml](NeuroML2/it.channel.nml)

**Comment by borismarin** [comment]
![ca_m_inf__h_inf](https://cloud.githubusercontent.com/assets/3452783/11020240/0864d990-8611-11e5-8297-a4735ba57745.png)
![ca_m_tau__h_tau](https://cloud.githubusercontent.com/assets/3452783/11020241/0879033e-8611-11e5-99b5-99307ae61824.png)
![it_m_inf__h_inf](https://cloud.githubusercontent.com/assets/3452783/11020242/087c6470-8611-11e5-9b1f-9dc06c510be7.png)
![it_m_tau__h_tau](https://cloud.githubusercontent.com/assets/3452783/11020243/088438c6-8611-11e5-9dc6-3015015a17f1.png)
![km_n_inf](https://cloud.githubusercontent.com/assets/3452783/11020244/08895e1e-8611-11e5-81c9-e9cc16a0c228.png)
![km_n_tau](https://cloud.githubusercontent.com/assets/3452783/11020245/088c0ede-8611-11e5-868f-ee3ffb2f1e46.png)
![kv_n_inf](https://cloud.githubusercontent.com/assets/3452783/11020246/088ea3d8-8611-11e5-8a28-ea90195f8286.png)
![kv_n_tau](https://cloud.githubusercontent.com/assets/3452783/11020247/08936f6c-8611-11e5-9e2d-cd04e4d0b97a.png)
![na_m_inf__h_inf](https://cloud.githubusercontent.com/assets/3452783/11020248/0896d008-8611-11e5-96b7-d48e58af8e46.png)
![na_m_tau__h_tau](https://cloud.githubusercontent.com/assets/3452783/11020249/089a5390-8611-11e5-89c3-3347b85297ef.png)
