### ISSUE TITLE
main.py fails with numpy 1.12 due to OfflinePoissonGroup in Brian 1

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/SmithEtAl2013-L23DendriticSpikes#3]
[main.py uses](https://github.com/OpenSourceBrain/SmithEtAl2013-L23DendriticSpikes/blob/090114edc422ed593892aa990c8d870c778fcb59/NEURON/main.py#L52) a [class OfflinePoissonGroup in Brian v1.4.3](https://github.com/brian-team/brian/blob/master/brian/directcontrol.py#L450) which calls [exponential in numpy.random](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.exponential.html).  In previous versions of numpy this gave a warning if 'size' was a float (ones(N) returns an array of 1.0s), but since numpy 1.12 this throws an error.

@mstimberg, @thesamovar I realise Brian 1 is no longer supported... Is there any equivalent of OfflinePoissonGroup in Brian2?

**Comment by mstimberg** [comment]
> @mstimberg, @thesamovar I realise Brian 1 is no longer supported... Is there any equivalent of OfflinePoissonGroup in Brian2?

No, this functionality does no longer exist (you could always use a `SpikeGeneratorGroup` and precalculate the spike times yourself). In the `main.py` code, it seems that the class is only used to calculate the spike times, i.e. it is not included in the actual network. I therefore think the easiest solution would be to use the spike time calculation code from the `OfflinePoissonGroup` directly, and substitute `np.ones(N)` by `np.ones(N, dtype=int)`.

**Comment by pgleeson** [comment]
@mstimberg thanks. I guessed this class might not exist in Brian2.

That's the approach I was planning to take, it is just that short class that's used from Brian and I can just copy that in, pointing to the original and then it removed the dependency on Brian.

**Comment by pgleeson** [comment]
I have removed the Brian dependency, and added an updated copy of the OfflinePoissonGroup class [here](https://github.com/OpenSourceBrain/SmithEtAl2013-L23DendriticSpikes/blob/68cae6b554af99b40db357fa43afd0981032b6f9/NEURON/main.py#L12).

main.py is being tested (with only Neuron) now: https://travis-ci.org/OpenSourceBrain/SmithEtAl2013-L23DendriticSpikes/jobs/226757897
